---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-do480
  labels:
    app: hello-do480
    name: hello-do480
  namespace: compreview-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-do480
      name: hello-do480
  template:
    metadata:
      labels:
        app: hello-do480
        name: hello-do480
    spec:
      containers:
      - name: hello-do480
        image: quay.io/harpasin/do480-hello:latest
        livenessProbe:
          periodSeconds: 60
---
